### ISSUE TITLE
react component

### ISSUE THREAD

**Issue by catalinmiron** [camwiegert/typical#4]
Hey @camwiegert,

Thanks for creating this great library, I've just published the `React` component that consumes your package. https://github.com/catalinmiron/react-typical (demo: https://catalinmiron.github.io/react-typical/) Thanks!

**Comment by camwiegert** [comment]
@catalinmiron Thanks! Looks great. I've added it to a "Related" section [in the readme](https://github.com/camwiegert/typical#related).
