### ISSUE TITLE
type speed

### ISSUE THREAD

**Issue by Shuunen** [camwiegert/typical#6]
Hi ^^ 

Would be great to customize the typing speed, what do you think ? Did you plan to let this be customizable ?

Thanks for your lib, love the minimalist ones like this ❤️

**Comment by camwiegert** [comment]
@Shuunen Thank you! I've thought about allowing the first argument to be an object with some options and a `target` key.

```js

const options = {
  target: document.querySelector('.typed-text'),
  speed: 40
};

type(options, 1000, 'Hello world!');
```

For the time being, I'm planning to keep it simple. If I see a lot of people asking to adjust the speed I will reconsider.

**Comment by abhiram11** [comment]
Hi! I'm using typical in React, but the text changes its alignment as soon as I add an emoji to the text (at the time it gets displayed).

Also, could you tell me how and where to use options when using this in React? I did the following : 
```js
function Banner() {
  const options = {
    target: document.querySelector(".typed-text"),
    speed: 4000,
};

return(
<>
<Typical
          loop={Infinity}
          wrapper="h4"
          steps={[
            "Experienced  abc 🚀",
            500,
            options,
            "Budding xyz💻",
            500,
            "Thanks  😊",
            500,
          ]}
        />
</>
)
}

```

P.s.: I am new to open source so I don't exactly know where to ask such a question.

**Comment by camwiegert** [comment]
@abhiram11 It looks like you're using the [React wrapper for this library](https://github.com/catalinmiron/react-typical), which has its own repo. I would consider opening an issue there.

Regarding your options object, typical itself doesn't take any options right now. The example above was just hypothetical and doesn't actually exist. Good luck!
